/*
 * This file is generated by jOOQ.
 */
package jooq.keys


import jooq.tables.Author
import jooq.tables.Books
import jooq.tables.records.AuthorRecord
import jooq.tables.records.BooksRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val KEY_AUTHOR_PRIMARY: UniqueKey<AuthorRecord> = Internal.createUniqueKey(Author.AUTHOR, DSL.name("KEY_author_PRIMARY"), arrayOf(Author.AUTHOR.ID), true)
val KEY_BOOKS_PRIMARY: UniqueKey<BooksRecord> = Internal.createUniqueKey(Books.BOOKS, DSL.name("KEY_books_PRIMARY"), arrayOf(Books.BOOKS.ID), true)
