/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records


import jooq.tables.Books

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BooksRecord() : UpdatableRecordImpl<BooksRecord>(Books.BOOKS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var bookName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var author: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised BooksRecord
     */
    constructor(id: Int? = null, bookName: String? = null, author: Int? = null): this() {
        this.id = id
        this.bookName = bookName
        this.author = author
        resetChangedOnNotNull()
    }
}
