/*
 * This file is generated by jOOQ.
 */
package jooq.tables.references


import jooq.tables.Author
import jooq.tables.Books



/**
 * The table <code>book_db.author</code>.
 */
val AUTHOR: Author = Author.AUTHOR

/**
 * The table <code>book_db.books</code>.
 */
val BOOKS: Books = Books.BOOKS
